### ISSUE TITLE
前端展示的坐标

### ISSUE THREAD

**Issue by dengshenkk** [mizuhokaga/jsplumb-dataLineage-vue#5]
我看示例代码中的坐标是写死在json中的, 如果调用api的话坐标信息是由后端提供吗? 前端能否自行计算?

**Comment by mizuhokaga** [comment]
1. 最初设计思路：
a.前端将带绘图窗口的长（length）和宽（width）这两个参数的请求发给后端接口
b.后端将通过拓扑算法 计算每个节点的的top和left
c.前端将返回结果渲染
d.拓扑算法具体内容我也是网上参考的,在这个文章里 https://blog.csdn.net/qq_44831907/article/details/128370539 ，具体再按自己需求修改。大致是将node集合和edges关系传入后生成带坐标的json
2. 前端计算就需要自行写方法了，计算肯定是可以计算的。考虑到节点过多的情况，为了减小前端压力，所以当时写法是坐标由后端计算~
